/**
 * Programmatic migrator: applies every pending migration in ./drizzle (generated by
 * `pnpm db:generate`, i.e. `drizzle-kit generate` — never hand-written, see
 * docs/DB-MIGRATION.md §1) against whatever `DATABASE_URL` points at, local Docker
 * MySQL or a hosted MySQL/TiDB Cloud instance alike. Run via `pnpm db:migrate`.
 */
import { migrate } from "drizzle-orm/mysql2/migrator";
import { getDb, closeDb } from "@/lib/db/client";

async function main(): Promise<void> {
  const db = getDb();
  await migrate(db, { migrationsFolder: "./drizzle" });
  console.log("Migrations applied.");
}

main()
  .catch((err) => {
    console.error("Migration failed:", err);
    process.exitCode = 1;
  })
  .finally(async () => {
    await closeDb();
  });
